<script setup lang="ts">
interface RankingEntry {
  Rank: string;
  Name: string;
  Country: string;
  A: string;
  B: string;
  C: string;
  Total: string;
  Award: string;
}

const rankingData: RankingEntry[] = [
  {
    Rank: "1",
    Name: "Wang Maohua",
    Country: "China",
    A: "100",
    B: "70",
    C: "100",
    Total: "270",
    Award: "Gold",
  },
  {
    Rank: "2",
    Name: "Hu Xiaohu",
    Country: "China",
    A: "84",
    B: "70",
    C: "100",
    Total: "254",
    Award: "Gold",
  },
  {
    Rank: "3",
    Name: "Lu Huarui",
    Country: "China",
    A: "83.7",
    B: "70",
    C: "100",
    Total: "253.7",
    Award: "Gold",
  },
  {
    Rank: "4",
    Name: "Mark Privodnov",
    Country: "Russia",
    A: "82.6",
    B: "70",
    C: "100",
    Total: "252.6",
    Award: "Gold",
  },
  {
    Rank: "5",
    Name: "Ian Bobrus",
    Country: "Kyrgyzstan",
    A: "78.1",
    B: "70",
    C: "100",
    Total: "248.1",
    Award: "Gold",
  },
  {
    Rank: "6",
    Name: "Wu Tongchun",
    Country: "China",
    A: "77.4",
    B: "70",
    C: "100",
    Total: "247.4",
    Award: "Gold",
  },
  {
    Rank: "7",
    Name: "Wang Yice",
    Country: "China",
    A: "77",
    B: "70",
    C: "100",
    Total: "247",
    Award: "Gold",
  },
  {
    Rank: "8",
    Name: "Zhao Shenghao",
    Country: "China",
    A: "75.7",
    B: "70",
    C: "100",
    Total: "245.7",
    Award: "Gold",
  },
  {
    Rank: "9",
    Name: "Alexander MacNeil",
    Country: "Russia",
    A: "75.8",
    B: "60.5",
    C: "100",
    Total: "236.3",
    Award: "Gold",
  },
  {
    Rank: "10",
    Name: "Nguyen Bui Duc Dung",
    Country: "Vietnam",
    A: "100",
    B: "36",
    C: "100",
    Total: "236",
    Award: "Gold",
  },
  {
    Rank: "11",
    Name: "Katsuki Ota",
    Country: "Japan",
    A: "61.5",
    B: "70",
    C: "100",
    Total: "231.5",
    Award: "Gold",
  },
  {
    Rank: "12",
    Name: "Petr Losev",
    Country: "Russia",
    A: "84.4",
    B: "46",
    C: "100",
    Total: "230.4",
    Award: "Gold",
  },
  {
    Rank: "13",
    Name: "Isaac Hew Kai Sheng",
    Country: "Malaysia",
    A: "57.9",
    B: "70",
    C: "100",
    Total: "227.9",
    Award: "Gold",
  },
  {
    Rank: "14",
    Name: "Daria Grekova",
    Country: "Russia",
    A: "54.9",
    B: "70",
    C: "100",
    Total: "224.9",
    Award: "Gold",
  },
  {
    Rank: "15",
    Name: "Daniel Weber",
    Country: "Israel",
    A: "78.1",
    B: "46",
    C: "100",
    Total: "224.1",
    Award: "Gold",
  },
  {
    Rank: "15",
    Name: "You Chan Lee",
    Country: "Republic of Korea",
    A: "78.1",
    B: "46",
    C: "100",
    Total: "224.1",
    Award: "Gold",
  },
  {
    Rank: "15",
    Name: "Lev Tciban",
    Country: "Russia",
    A: "78.1",
    B: "46",
    C: "100",
    Total: "224.1",
    Award: "Gold",
  },
  {
    Rank: "18",
    Name: "Kwan Yung Ho",
    Country: "Hong Kong",
    A: "76.5",
    B: "46",
    C: "100",
    Total: "222.5",
    Award: "Silver",
  },
  {
    Rank: "18",
    Name: "Gimran Abdullin",
    Country: "Russia",
    A: "76.5",
    B: "46",
    C: "100",
    Total: "222.5",
    Award: "Silver",
  },
  {
    Rank: "20",
    Name: "Parsa Golestani",
    Country: "Iran",
    A: "82.6",
    B: "22",
    C: "100",
    Total: "204.6",
    Award: "Silver",
  },
  {
    Rank: "21",
    Name: "Tzu-Chiao Yen",
    Country: "Taiwan",
    A: "56.3",
    B: "46",
    C: "100",
    Total: "202.3",
    Award: "Silver",
  },
  {
    Rank: "22",
    Name: "Sun Beichen",
    Country: "Singapore",
    A: "54.9",
    B: "46",
    C: "100",
    Total: "200.9",
    Award: "Silver",
  },
  {
    Rank: "23",
    Name: "Mingyu Woo",
    Country: "Republic of Korea",
    A: "78.1",
    B: "22",
    C: "100",
    Total: "200.1",
    Award: "Silver",
  },
  {
    Rank: "24",
    Name: "Lai Hong Tung Honrich",
    Country: "Hong Kong",
    A: "78.1",
    B: "46",
    C: "74",
    Total: "198.1",
    Award: "Silver",
  },
  {
    Rank: "24",
    Name: "Kelven Nathanael",
    Country: "Indonesia",
    A: "78.1",
    B: "46",
    C: "74",
    Total: "198.1",
    Award: "Silver",
  },
  {
    Rank: "24",
    Name: "Koudai Sakayama",
    Country: "Japan",
    A: "78.1",
    B: "46",
    C: "74",
    Total: "198.1",
    Award: "Silver",
  },
  {
    Rank: "24",
    Name: "Chun-Yao Shih",
    Country: "Taiwan",
    A: "78.1",
    B: "46",
    C: "74",
    Total: "198.1",
    Award: "Silver",
  },
  {
    Rank: "28",
    Name: "Le Kien Thanh",
    Country: "Vietnam",
    A: "75.5",
    B: "46",
    C: "74",
    Total: "195.5",
    Award: "Silver",
  },
  {
    Rank: "29",
    Name: "Chi-En Chen",
    Country: "Taiwan",
    A: "82.5",
    B: "12",
    C: "100",
    Total: "194.5",
    Award: "Silver",
  },
  {
    Rank: "30",
    Name: "Tsovak Yegoryan",
    Country: "Armenia",
    A: "56",
    B: "36",
    C: "100",
    Total: "192",
    Award: "Silver",
  },
  {
    Rank: "31",
    Name: "Eunho Cho",
    Country: "Republic of Korea",
    A: "78.1",
    B: "12",
    C: "100",
    Total: "190.1",
    Award: "Silver",
  },
  {
    Rank: "31",
    Name: "Yi-An Wang",
    Country: "Taiwan",
    A: "78.1",
    B: "12",
    C: "100",
    Total: "190.1",
    Award: "Silver",
  },
  {
    Rank: "31",
    Name: "Dang Huy Hau",
    Country: "Vietnam",
    A: "78.1",
    B: "12",
    C: "100",
    Total: "190.1",
    Award: "Silver",
  },
  {
    Rank: "34",
    Name: "Franklin Filbert Irwan",
    Country: "Indonesia",
    A: "76.5",
    B: "12",
    C: "100",
    Total: "188.5",
    Award: "Silver",
  },
  {
    Rank: "35",
    Name: "Ho Shun Ngai",
    Country: "Hong Kong",
    A: "78.1",
    B: "36",
    C: "74",
    Total: "188.1",
    Award: "Silver",
  },
  {
    Rank: "36",
    Name: "Sihyung Park",
    Country: "Republic of Korea",
    A: "78.1",
    B: "6",
    C: "100",
    Total: "184.1",
    Award: "Silver",
  },
  {
    Rank: "37",
    Name: "Takumi Yamamoto",
    Country: "Japan",
    A: "71.6",
    B: "12",
    C: "100",
    Total: "183.6",
    Award: "Silver",
  },
  {
    Rank: "38",
    Name: "Khor Yan Xun",
    Country: "Malaysia",
    A: "25",
    B: "57.7",
    C: "100",
    Total: "182.7",
    Award: "Silver",
  },
  {
    Rank: "39",
    Name: "Nathan Zhou",
    Country: "Australia",
    A: "25",
    B: "46",
    C: "100",
    Total: "171",
    Award: "Silver",
  },
  {
    Rank: "39",
    Name: "Hanif Achdan Pietoyo",
    Country: "Indonesia",
    A: "25",
    B: "46",
    C: "100",
    Total: "171",
    Award: "Silver",
  },
  {
    Rank: "39",
    Name: "Hamid Shafizadeh",
    Country: "Iran",
    A: "25",
    B: "46",
    C: "100",
    Total: "171",
    Award: "Silver",
  },
  {
    Rank: "39",
    Name: "Daniel Priness",
    Country: "Israel",
    A: "25",
    B: "46",
    C: "100",
    Total: "171",
    Award: "Silver",
  },
  {
    Rank: "39",
    Name: "Keisuke Kakehi",
    Country: "Japan",
    A: "25",
    B: "46",
    C: "100",
    Total: "171",
    Award: "Silver",
  },
  {
    Rank: "39",
    Name: "Aldiyar Seitbay",
    Country: "Kazakhstan",
    A: "25",
    B: "46",
    C: "100",
    Total: "171",
    Award: "Silver",
  },
  {
    Rank: "39",
    Name: "Ding Chenghao",
    Country: "Singapore",
    A: "25",
    B: "46",
    C: "100",
    Total: "171",
    Award: "Silver",
  },
  {
    Rank: "46",
    Name: "Yash Thakker",
    Country: "India",
    A: "58.8",
    B: "12",
    C: "100",
    Total: "170.8",
    Award: "Silver",
  },
  {
    Rank: "47",
    Name: "Brian Xiao Boyang",
    Country: "Singapore",
    A: "25",
    B: "70",
    C: "74",
    Total: "169",
    Award: "Silver",
  },
  {
    Rank: "48",
    Name: "Jerome Austin Te",
    Country: "Philippines",
    A: "78.1",
    B: "36",
    C: "54",
    Total: "168.1",
    Award: "Silver",
  },
  {
    Rank: "49",
    Name: "Tsung-Yi Tsai",
    Country: "Taiwan",
    A: "56.5",
    B: "36",
    C: "74",
    Total: "166.5",
    Award: "Silver",
  },
  {
    Rank: "50",
    Name: "Mak Chun Hin Ivan",
    Country: "Hong Kong",
    A: "78.1",
    B: "12",
    C: "74",
    Total: "164.1",
    Award: "Silver",
  },
  {
    Rank: "51",
    Name: "Maxim Tsoy",
    Country: "Kazakhstan",
    A: "78.1",
    B: "46",
    C: "39",
    Total: "163.1",
    Award: "Silver",
  },
  {
    Rank: "52",
    Name: "Jirat Chiaranaipanich",
    Country: "Thailand",
    A: "76.6",
    B: "12",
    C: "74",
    Total: "162.6",
    Award: "Bronze",
  },
  {
    Rank: "53",
    Name: "Ryan Shaw",
    Country: "Singapore",
    A: "25",
    B: "36",
    C: "100",
    Total: "161",
    Award: "Bronze",
  },
  {
    Rank: "54",
    Name: "Aykhan Damirli",
    Country: "Azerbaijan",
    A: "78.1",
    B: "22",
    C: "54",
    Total: "154.1",
    Award: "Bronze",
  },
  {
    Rank: "55",
    Name: "Kittiphat Pongarunotai",
    Country: "Thailand",
    A: "8",
    B: "46",
    C: "100",
    Total: "154",
    Award: "Bronze",
  },
  {
    Rank: "56",
    Name: "Mani Zare",
    Country: "Iran",
    A: "52.8",
    B: "70",
    C: "28",
    Total: "150.8",
    Award: "Bronze",
  },
  {
    Rank: "57",
    Name: "Ahmed Gamal Kamel Mohamed Osman",
    Country: "Egypt",
    A: "25",
    B: "70",
    C: "54",
    Total: "149",
    Award: "Bronze",
  },
  {
    Rank: "58",
    Name: "Idan Rosenzweig",
    Country: "Israel",
    A: "67.3",
    B: "6",
    C: "74",
    Total: "147.3",
    Award: "Bronze",
  },
  {
    Rank: "59",
    Name: "Debojoti Das Soumya",
    Country: "Bangladesh",
    A: "25",
    B: "22",
    C: "100",
    Total: "147",
    Award: "Bronze",
  },
  {
    Rank: "59",
    Name: "Mina Ragy Fouad",
    Country: "Egypt",
    A: "51",
    B: "22",
    C: "74",
    Total: "147",
    Award: "Bronze",
  },
  {
    Rank: "59",
    Name: "Lu Yi Fung",
    Country: "Hong Kong",
    A: "25",
    B: "22",
    C: "100",
    Total: "147",
    Award: "Bronze",
  },
  {
    Rank: "59",
    Name: "Woohyun Jung",
    Country: "Republic of Korea",
    A: "25",
    B: "22",
    C: "100",
    Total: "147",
    Award: "Bronze",
  },
  {
    Rank: "59",
    Name: "Heng Liao",
    Country: "Taiwan",
    A: "25",
    B: "22",
    C: "100",
    Total: "147",
    Award: "Bronze",
  },
  {
    Rank: "64",
    Name: "Adhitya Mangudy Venkata Ganesh",
    Country: "India",
    A: "25",
    B: "46",
    C: "74",
    Total: "145",
    Award: "Bronze",
  },
  {
    Rank: "64",
    Name: "Rei Karashima",
    Country: "Japan",
    A: "25",
    B: "46",
    C: "74",
    Total: "145",
    Award: "Bronze",
  },
  {
    Rank: "64",
    Name: "Kunthee Yongvanich",
    Country: "Thailand",
    A: "25",
    B: "46",
    C: "74",
    Total: "145",
    Award: "Bronze",
  },
  {
    Rank: "64",
    Name: "Petewat Chaoha",
    Country: "Thailand",
    A: "25",
    B: "46",
    C: "74",
    Total: "145",
    Award: "Bronze",
  },
  {
    Rank: "64",
    Name: "Thawin Tengamnuay",
    Country: "Thailand",
    A: "25",
    B: "46",
    C: "74",
    Total: "145",
    Award: "Bronze",
  },
  {
    Rank: "64",
    Name: "Ninh Quang Thang",
    Country: "Vietnam",
    A: "25",
    B: "46",
    C: "74",
    Total: "145",
    Award: "Bronze",
  },
  {
    Rank: "70",
    Name: "Aufan Ahmad Mumtaza",
    Country: "Indonesia",
    A: "82.6",
    B: "46",
    C: "16",
    Total: "144.6",
    Award: "Bronze",
  },
  {
    Rank: "71",
    Name: "Victor Coen",
    Country: "New Zealand",
    A: "28.7",
    B: "12",
    C: "100",
    Total: "140.7",
    Award: "Bronze",
  },
  {
    Rank: "72",
    Name: "Wei Bin Ang",
    Country: "Singapore",
    A: "44.6",
    B: "22",
    C: "74",
    Total: "140.6",
    Award: "Bronze",
  },
  {
    Rank: "73",
    Name: "Matthew Shi Xuan Lin",
    Country: "Australia",
    A: "78.1",
    B: "46",
    C: "16",
    Total: "140.1",
    Award: "Bronze",
  },
  {
    Rank: "73",
    Name: "Choy Tsz Chai Berton",
    Country: "Hong Kong",
    A: "78.1",
    B: "46",
    C: "16",
    Total: "140.1",
    Award: "Bronze",
  },
  {
    Rank: "73",
    Name: "Araya Luanseng",
    Country: "Thailand",
    A: "78.1",
    B: "46",
    C: "16",
    Total: "140.1",
    Award: "Bronze",
  },
  {
    Rank: "76",
    Name: "Zhao Yaoqi",
    Country: "Singapore",
    A: "77",
    B: "46",
    C: "16",
    Total: "139",
    Award: "Bronze",
  },
  {
    Rank: "77",
    Name: "Nguyen Huy Phong",
    Country: "Vietnam",
    A: "57.1",
    B: "6",
    C: "74",
    Total: "137.1",
    Award: "Bronze",
  },
  {
    Rank: "78",
    Name: "Martin Khachatryan",
    Country: "Armenia",
    A: "25",
    B: "12",
    C: "100",
    Total: "137",
    Award: "Bronze",
  },
  {
    Rank: "78",
    Name: "Tigran Matsakyan",
    Country: "Armenia",
    A: "25",
    B: "12",
    C: "100",
    Total: "137",
    Award: "Bronze",
  },
  {
    Rank: "78",
    Name: "Ido Noam",
    Country: "Israel",
    A: "25",
    B: "12",
    C: "100",
    Total: "137",
    Award: "Bronze",
  },
  {
    Rank: "78",
    Name: "Erkhem Ganzorig",
    Country: "Mongolia",
    A: "25",
    B: "12",
    C: "100",
    Total: "137",
    Award: "Bronze",
  },
  {
    Rank: "82",
    Name: "Toshtemirov Javohir",
    Country: "Uzbekistan",
    A: "25",
    B: "6",
    C: "100",
    Total: "131",
    Award: "Bronze",
  },
  {
    Rank: "82",
    Name: "Akbarov Izzat",
    Country: "Uzbekistan",
    A: "25",
    B: "6",
    C: "100",
    Total: "131",
    Award: "Bronze",
  },
  {
    Rank: "84",
    Name: "Hans Gabriel De Vera",
    Country: "Philippines",
    A: "78.1",
    B: "36",
    C: "16",
    Total: "130.1",
    Award: "Bronze",
  },
  {
    Rank: "84",
    Name: "Qadirbergenov Timur",
    Country: "Uzbekistan",
    A: "78.1",
    B: "36",
    C: "16",
    Total: "130.1",
    Award: "Bronze",
  },
  {
    Rank: "86",
    Name: "Raz Dvora",
    Country: "Israel",
    A: "59.7",
    B: "46",
    C: "24",
    Total: "129.7",
    Award: "Bronze",
  },
  {
    Rank: "87",
    Name: "Ho Janson",
    Country: "Malaysia",
    A: "82.6",
    B: "46",
    C: "0",
    Total: "128.6",
    Award: "Bronze",
  },
  {
    Rank: "88",
    Name: "Yuya Hirasawa",
    Country: "Japan",
    A: "25",
    B: "46",
    C: "54",
    Total: "125",
    Award: "Bronze",
  },
  {
    Rank: "88",
    Name: "Amarsanaa Gantumur",
    Country: "Mongolia",
    A: "25",
    B: "0",
    C: "100",
    Total: "125",
    Award: "Bronze",
  },
  {
    Rank: "88",
    Name: "Kyujin Kim",
    Country: "Republic of Korea",
    A: "25",
    B: "0",
    C: "100",
    Total: "125",
    Award: "Bronze",
  },
  {
    Rank: "91",
    Name: "Eric Liu",
    Country: "New Zealand",
    A: "69",
    B: "46",
    C: "5",
    Total: "120",
    Award: "Bronze",
  },
  {
    Rank: "92",
    Name: "Nguyen Xuan Chi Thanh",
    Country: "Vietnam",
    A: "57.2",
    B: "46",
    C: "16",
    Total: "119.2",
    Award: "Bronze",
  },
  {
    Rank: "93",
    Name: "Aleks Grigoryan",
    Country: "Armenia",
    A: "54.6",
    B: "46",
    C: "16",
    Total: "116.6",
    Award: "Bronze",
  },
  {
    Rank: "94",
    Name: "Yoav Shamay",
    Country: "Israel",
    A: "63.9",
    B: "46",
    C: "5",
    Total: "114.9",
    Award: "Bronze",
  },
  {
    Rank: "95",
    Name: "Rainer Evan Rusly",
    Country: "Indonesia",
    A: "8",
    B: "6",
    C: "100",
    Total: "114",
    Award: "Bronze",
  },
  {
    Rank: "95",
    Name: "Adilkhan Kadyrov",
    Country: "Kyrgyzstan",
    A: "8",
    B: "6",
    C: "100",
    Total: "114",
    Award: "Bronze",
  },
  {
    Rank: "97",
    Name: "Hamed Ghaffari",
    Country: "Iran",
    A: "25",
    B: "70",
    C: "16",
    Total: "111",
    Award: "Bronze",
  },
  {
    Rank: "98",
    Name: "Dinmukhammed Talkat",
    Country: "Kazakhstan",
    A: "25",
    B: "46",
    C: "39",
    Total: "110",
    Award: "Bronze",
  },
  {
    Rank: "99",
    Name: "Yuichiro Furuse",
    Country: "Malaysia",
    A: "73.1",
    B: "30",
    C: "5",
    Total: "108.1",
    Award: "Bronze",
  },
  {
    Rank: "100",
    Name: "Kong Hoi Mun",
    Country: "Malaysia",
    A: "8",
    B: "0",
    C: "100",
    Total: "108",
    Award: "Bronze",
  },
  {
    Rank: "101",
    Name: "Hu Bang Zhen",
    Country: "Malaysia",
    A: "0",
    B: "6",
    C: "100",
    Total: "106",
    Award: "Official participation",
  },
  {
    Rank: "102",
    Name: "Chris Qiu",
    Country: "Australia",
    A: "78.1",
    B: "22",
    C: "5",
    Total: "105.1",
    Award: "Official participation",
  },
  {
    Rank: "103",
    Name: "Rahmatullayev Ulug'bek",
    Country: "Uzbekistan",
    A: "76.7",
    B: "12",
    C: "16",
    Total: "104.7",
    Award: "Official participation",
  },
  {
    Rank: "104",
    Name: "Amirali Asgari",
    Country: "Iran",
    A: "54.3",
    B: "46",
    C: "0",
    Total: "100.3",
    Award: "Official participation",
  },
  {
    Rank: "105",
    Name: "Yup Meng Quek",
    Country: "Australia",
    A: "25",
    B: "36",
    C: "39",
    Total: "100",
    Award: "Official participation",
  },
  {
    Rank: "106",
    Name: "Chi Him Kuan",
    Country: "Macau",
    A: "78.1",
    B: "12",
    C: "5",
    Total: "95.1",
    Award: "Official participation",
  },
  {
    Rank: "107",
    Name: "Inoyatov Ismoilmirzo",
    Country: "Uzbekistan",
    A: "8",
    B: "12",
    C: "74",
    Total: "94",
    Award: "Official participation",
  },
  {
    Rank: "108",
    Name: "Muhammad Umair Ahmad Mirza",
    Country: "Pakistan",
    A: "75.5",
    B: "12",
    C: "5",
    Total: "92.5",
    Award: "Official participation",
  },
  {
    Rank: "109",
    Name: "Archit Manas",
    Country: "India",
    A: "45.7",
    B: "46",
    C: "0",
    Total: "91.7",
    Award: "Official participation",
  },
  {
    Rank: "110",
    Name: "Mann Avnish Shah",
    Country: "India",
    A: "25",
    B: "12",
    C: "54",
    Total: "91",
    Award: "Official participation",
  },
  {
    Rank: "111",
    Name: "Nurlybek Yesbolganov",
    Country: "Kazakhstan",
    A: "25",
    B: "0",
    C: "63",
    Total: "88",
    Award: "Official participation",
  },
  {
    Rank: "112",
    Name: "Vladimeri Prangishvili",
    Country: "Georgia",
    A: "25",
    B: "46",
    C: "16",
    Total: "87",
    Award: "Official participation",
  },
  {
    Rank: "112",
    Name: "Aviansh Verma",
    Country: "India",
    A: "25",
    B: "46",
    C: "16",
    Total: "87",
    Award: "Official participation",
  },
  {
    Rank: "112",
    Name: "Naveen Pramod Kulkarni",
    Country: "India",
    A: "25",
    B: "46",
    C: "16",
    Total: "87",
    Award: "Official participation",
  },
  {
    Rank: "112",
    Name: "Luvidi Pranawa Alghari",
    Country: "Indonesia",
    A: "25",
    B: "46",
    C: "16",
    Total: "87",
    Award: "Official participation",
  },
  {
    Rank: "112",
    Name: "Issatay Ismagzi",
    Country: "Kazakhstan",
    A: "25",
    B: "46",
    C: "16",
    Total: "87",
    Award: "Official participation",
  },
  {
    Rank: "112",
    Name: "Irmuun Chinbat",
    Country: "Mongolia",
    A: "25",
    B: "46",
    C: "16",
    Total: "87",
    Award: "Official participation",
  },
  {
    Rank: "112",
    Name: "Tymon Mieszkowski",
    Country: "New Zealand",
    A: "25",
    B: "46",
    C: "16",
    Total: "87",
    Award: "Official participation",
  },
  {
    Rank: "112",
    Name: "Ahmed Imran Malik",
    Country: "Pakistan",
    A: "25",
    B: "46",
    C: "16",
    Total: "87",
    Award: "Official participation",
  },
  {
    Rank: "112",
    Name: "Mohammad Deeb Ahmad Alsaleh",
    Country: "Syria",
    A: "25",
    B: "46",
    C: "16",
    Total: "87",
    Award: "Official participation",
  },
  {
    Rank: "121",
    Name: "Vladislav Possin",
    Country: "Kazakhstan",
    A: "25",
    B: "22",
    C: "39",
    Total: "86",
    Award: "Official participation",
  },
  {
    Rank: "122",
    Name: "Nurislam Karypzhanov",
    Country: "Kyrgyzstan",
    A: "25",
    B: "6",
    C: "54",
    Total: "85",
    Award: "Official participation",
  },
  {
    Rank: "123",
    Name: "Moez Mahmoud Mohamed",
    Country: "Egypt",
    A: "8",
    B: "12",
    C: "63",
    Total: "83",
    Award: "Official participation",
  },
  {
    Rank: "124",
    Name: "Sunnatov Asilbek",
    Country: "Uzbekistan",
    A: "51.4",
    B: "12",
    C: "16",
    Total: "79.4",
    Award: "Official participation",
  },
  {
    Rank: "125",
    Name: "Richie Yang",
    Country: "Australia",
    A: "25",
    B: "36",
    C: "16",
    Total: "77",
    Award: "Official participation",
  },
  {
    Rank: "125",
    Name: "Mate Rekhviashvili",
    Country: "Georgia",
    A: "25",
    B: "36",
    C: "16",
    Total: "77",
    Award: "Official participation",
  },
  {
    Rank: "125",
    Name: "Amir Mohammad Namdar",
    Country: "Iran",
    A: "25",
    B: "36",
    C: "16",
    Total: "77",
    Award: "Official participation",
  },
  {
    Rank: "125",
    Name: "Zi Yan Wang",
    Country: "Macau",
    A: "25",
    B: "36",
    C: "16",
    Total: "77",
    Award: "Official participation",
  },
  {
    Rank: "125",
    Name: "Ghulam Junaid",
    Country: "Pakistan",
    A: "25",
    B: "36",
    C: "16",
    Total: "77",
    Award: "Official participation",
  },
  {
    Rank: "125",
    Name: "EdRonn James Panti",
    Country: "Philippines",
    A: "25",
    B: "36",
    C: "16",
    Total: "77",
    Award: "Official participation",
  },
  {
    Rank: "131",
    Name: "Giorgi Bulauri",
    Country: "Georgia",
    A: "25",
    B: "46",
    C: "5",
    Total: "76",
    Award: "Official participation",
  },
  {
    Rank: "131",
    Name: "Nikoloz Melikishvili",
    Country: "Georgia",
    A: "25",
    B: "46",
    C: "5",
    Total: "76",
    Award: "Official participation",
  },
  {
    Rank: "131",
    Name: "Alihan Aidarbekov",
    Country: "Kyrgyzstan",
    A: "25",
    B: "46",
    C: "5",
    Total: "76",
    Award: "Official participation",
  },
  {
    Rank: "134",
    Name: "Abdulrahman Mahmoud Sfar",
    Country: "Syria",
    A: "57.9",
    B: "12",
    C: "5",
    Total: "74.9",
    Award: "Official participation",
  },
  {
    Rank: "135",
    Name: "Jawad Akbar Khan",
    Country: "Pakistan",
    A: "25",
    B: "6",
    C: "43",
    Total: "74",
    Award: "Official participation",
  },
  {
    Rank: "136",
    Name: "ChengHou Tang",
    Country: "Macau",
    A: "56.5",
    B: "12",
    C: "5",
    Total: "73.5",
    Award: "Official participation",
  },
  {
    Rank: "137",
    Name: "George Chen",
    Country: "Australia",
    A: "55.9",
    B: "12",
    C: "5",
    Total: "72.9",
    Award: "Official participation",
  },
  {
    Rank: "138",
    Name: "Abdullah Mohammad Abdullah",
    Country: "Syria",
    A: "25",
    B: "22",
    C: "24",
    Total: "71",
    Award: "Official participation",
  },
  {
    Rank: "138",
    Name: "Rakhimov Amir Ravshanovich",
    Country: "Tajikistan",
    A: "25",
    B: "46",
    C: "0",
    Total: "71",
    Award: "Official participation",
  },
  {
    Rank: "140",
    Name: "Andria Vasadze",
    Country: "Georgia",
    A: "29.2",
    B: "36",
    C: "5",
    Total: "70.2",
    Award: "Official participation",
  },
  {
    Rank: "141",
    Name: "Omar Sameh Fawzy Elmasry",
    Country: "Egypt",
    A: "25",
    B: "36",
    C: "5",
    Total: "66",
    Award: "Official participation",
  },
  {
    Rank: "141",
    Name: "Abdullah Ishfaq",
    Country: "Pakistan",
    A: "25",
    B: "36",
    C: "5",
    Total: "66",
    Award: "Official participation",
  },
  {
    Rank: "141",
    Name: "Mateo Sebastian Campos",
    Country: "Philippines",
    A: "25",
    B: "36",
    C: "5",
    Total: "66",
    Award: "Official participation",
  },
  {
    Rank: "141",
    Name: "Troy Dylan Serapio",
    Country: "Philippines",
    A: "25",
    B: "36",
    C: "5",
    Total: "66",
    Award: "Official participation",
  },
  {
    Rank: "141",
    Name: "Sultan Abdulrahman Alaiban",
    Country: "Saudi Arabia",
    A: "25",
    B: "36",
    C: "5",
    Total: "66",
    Award: "Official participation",
  },
  {
    Rank: "146",
    Name: "Pok Hong Lam",
    Country: "Macau",
    A: "25",
    B: "22",
    C: "16",
    Total: "63",
    Award: "Official participation",
  },
  {
    Rank: "146",
    Name: "Muhammad Saram",
    Country: "Pakistan",
    A: "25",
    B: "22",
    C: "16",
    Total: "63",
    Award: "Official participation",
  },
  {
    Rank: "146",
    Name: "Malitha Bandara",
    Country: "Sri Lanka",
    A: "25",
    B: "22",
    C: "16",
    Total: "63",
    Award: "Official participation",
  },
  {
    Rank: "149",
    Name: "Omar Ahmed Abdelaziz Mohamed Elbayoumi",
    Country: "Egypt",
    A: "25",
    B: "12",
    C: "24",
    Total: "61",
    Award: "Official participation",
  },
  {
    Rank: "150",
    Name: "Davit Dzadzamia",
    Country: "Georgia",
    A: "8",
    B: "46",
    C: "5",
    Total: "59",
    Award: "Official participation",
  },
  {
    Rank: "150",
    Name: "Hang Chi Ng",
    Country: "Macau",
    A: "8",
    B: "46",
    C: "5",
    Total: "59",
    Award: "Official participation",
  },
  {
    Rank: "150",
    Name: "Mohammad Nasser Alasmari",
    Country: "Saudi Arabia",
    A: "8",
    B: "12",
    C: "39",
    Total: "59",
    Award: "Official participation",
  },
  {
    Rank: "153",
    Name: "Akib Azmain Turja",
    Country: "Bangladesh",
    A: "45.8",
    B: "6",
    C: "5",
    Total: "56.8",
    Award: "Official participation",
  },
  {
    Rank: "154",
    Name: "Haidara Talal Almakdid",
    Country: "Syria",
    A: "50.2",
    B: "6",
    C: "0",
    Total: "56.2",
    Award: "Official participation",
  },
  {
    Rank: "155",
    Name: "Abdulaziz Lebiev",
    Country: "Kyrgyzstan",
    A: "27.2",
    B: "12",
    C: "16",
    Total: "55.2",
    Award: "Official participation",
  },
  {
    Rank: "156",
    Name: "Elvin Imanli",
    Country: "Azerbaijan",
    A: "25",
    B: "12",
    C: "16",
    Total: "53",
    Award: "Official participation",
  },
  {
    Rank: "156",
    Name: "Hasan Valiyev",
    Country: "Azerbaijan",
    A: "25",
    B: "12",
    C: "16",
    Total: "53",
    Award: "Official participation",
  },
  {
    Rank: "156",
    Name: "Ahmed Sameh Gomaa Abd El Sal Aref",
    Country: "Egypt",
    A: "25",
    B: "12",
    C: "16",
    Total: "53",
    Award: "Official participation",
  },
  {
    Rank: "156",
    Name: "Hossam Sherif Ahmed",
    Country: "Egypt",
    A: "25",
    B: "12",
    C: "16",
    Total: "53",
    Award: "Official participation",
  },
  {
    Rank: "156",
    Name: "Phares Mostafa Saad Abdallah Hamad",
    Country: "Egypt",
    A: "25",
    B: "12",
    C: "16",
    Total: "53",
    Award: "Official participation",
  },
  {
    Rank: "156",
    Name: "Dzhanikeev Said",
    Country: "Kyrgyzstan",
    A: "25",
    B: "12",
    C: "16",
    Total: "53",
    Award: "Official participation",
  },
  {
    Rank: "156",
    Name: "Ervin Joshua Bautista",
    Country: "Philippines",
    A: "25",
    B: "12",
    C: "16",
    Total: "53",
    Award: "Official participation",
  },
  {
    Rank: "156",
    Name: "John Lorenz Nunez",
    Country: "Philippines",
    A: "25",
    B: "12",
    C: "16",
    Total: "53",
    Award: "Official participation",
  },
  {
    Rank: "156",
    Name: "Lance Patrick Abarquez",
    Country: "Philippines",
    A: "25",
    B: "12",
    C: "16",
    Total: "53",
    Award: "Official participation",
  },
  {
    Rank: "156",
    Name: "Praveen Charuka Athauda Arachchi",
    Country: "Sri Lanka",
    A: "25",
    B: "12",
    C: "16",
    Total: "53",
    Award: "Official participation",
  },
  {
    Rank: "156",
    Name: "Amr Belal Abbara",
    Country: "Syria",
    A: "25",
    B: "12",
    C: "16",
    Total: "53",
    Award: "Official participation",
  },
  {
    Rank: "156",
    Name: "Bishr Ammar Joukhadar",
    Country: "Syria",
    A: "25",
    B: "12",
    C: "16",
    Total: "53",
    Award: "Official participation",
  },
  {
    Rank: "156",
    Name: "Hadi Bassem Suleiman",
    Country: "Syria",
    A: "25",
    B: "12",
    C: "16",
    Total: "53",
    Award: "Official participation",
  },
  {
    Rank: "156",
    Name: "Judy Saleh Wafai",
    Country: "Syria",
    A: "25",
    B: "12",
    C: "16",
    Total: "53",
    Award: "Official participation",
  },
  {
    Rank: "156",
    Name: "Younis Shadi Dwai",
    Country: "Syria",
    A: "25",
    B: "12",
    C: "16",
    Total: "53",
    Award: "Official participation",
  },
  {
    Rank: "156",
    Name: "Rakhimov Azam Dalerovich",
    Country: "Tajikistan",
    A: "25",
    B: "12",
    C: "16",
    Total: "53",
    Award: "Official participation",
  },
  {
    Rank: "172",
    Name: "Ali Aliyev",
    Country: "Azerbaijan",
    A: "25",
    B: "12",
    C: "13",
    Total: "50",
    Award: "Official participation",
  },
  {
    Rank: "173",
    Name: "Ziyad Yousef Obaid Alharbi",
    Country: "Saudi Arabia",
    A: "8",
    B: "36",
    C: "5",
    Total: "49",
    Award: "Official participation",
  },
  {
    Rank: "173",
    Name: "Muhammadiev Muso",
    Country: "Tajikistan",
    A: "25",
    B: "0",
    C: "24",
    Total: "49",
    Award: "Official participation",
  },
  {
    Rank: "175",
    Name: "Arman Kirakosyan",
    Country: "Armenia",
    A: "25",
    B: "6",
    C: "16",
    Total: "47",
    Award: "Official participation",
  },
  {
    Rank: "175",
    Name: "Fijaj Rahman",
    Country: "Bangladesh",
    A: "25",
    B: "6",
    C: "16",
    Total: "47",
    Award: "Official participation",
  },
  {
    Rank: "175",
    Name: "Battsagaan Bat-Eruult",
    Country: "Mongolia",
    A: "25",
    B: "6",
    C: "16",
    Total: "47",
    Award: "Official participation",
  },
  {
    Rank: "175",
    Name: "Munkhtur Erdenebat",
    Country: "Mongolia",
    A: "25",
    B: "6",
    C: "16",
    Total: "47",
    Award: "Official participation",
  },
  {
    Rank: "175",
    Name: "Abdulrahman Abdulhamid Ali AlGhamdi",
    Country: "Saudi Arabia",
    A: "25",
    B: "6",
    C: "16",
    Total: "47",
    Award: "Official participation",
  },
  {
    Rank: "175",
    Name: "Halymmuhammet Annageldyyev",
    Country: "Turkmenistan",
    A: "25",
    B: "6",
    C: "16",
    Total: "47",
    Award: "Official participation",
  },
  {
    Rank: "181",
    Name: "Tuvshinbayar Mandakh",
    Country: "Mongolia",
    A: "25",
    B: "6",
    C: "13",
    Total: "44",
    Award: "Official participation",
  },
  {
    Rank: "182",
    Name: "Mher Kalashyan",
    Country: "Armenia",
    A: "25",
    B: "12",
    C: "5",
    Total: "42",
    Award: "Official participation",
  },
  {
    Rank: "182",
    Name: "Vahan Abrahamyan",
    Country: "Armenia",
    A: "25",
    B: "12",
    C: "5",
    Total: "42",
    Award: "Official participation",
  },
  {
    Rank: "182",
    Name: "Ahmad Gambarli",
    Country: "Azerbaijan",
    A: "25",
    B: "12",
    C: "5",
    Total: "42",
    Award: "Official participation",
  },
  {
    Rank: "182",
    Name: "Elay Verdiyev",
    Country: "Azerbaijan",
    A: "25",
    B: "12",
    C: "5",
    Total: "42",
    Award: "Official participation",
  },
  {
    Rank: "182",
    Name: "Rahidil Bayramli",
    Country: "Azerbaijan",
    A: "25",
    B: "12",
    C: "5",
    Total: "42",
    Award: "Official participation",
  },
  {
    Rank: "182",
    Name: "Rza Aghayev",
    Country: "Azerbaijan",
    A: "25",
    B: "12",
    C: "5",
    Total: "42",
    Award: "Official participation",
  },
  {
    Rank: "182",
    Name: "Khalid Mohammad Alabdullatif",
    Country: "Saudi Arabia",
    A: "25",
    B: "12",
    C: "5",
    Total: "42",
    Award: "Official participation",
  },
  {
    Rank: "182",
    Name: "Omar Abdulsalam Mohammed bin Muharib",
    Country: "Saudi Arabia",
    A: "25",
    B: "12",
    C: "5",
    Total: "42",
    Award: "Official participation",
  },
  {
    Rank: "182",
    Name: "Saad Bandar Nasser Alarifi",
    Country: "Saudi Arabia",
    A: "25",
    B: "12",
    C: "5",
    Total: "42",
    Award: "Official participation",
  },
  {
    Rank: "182",
    Name: "Azizmurodzoda Shahron",
    Country: "Tajikistan",
    A: "25",
    B: "12",
    C: "5",
    Total: "42",
    Award: "Official participation",
  },
  {
    Rank: "182",
    Name: "Jelaleddin Narkulyev",
    Country: "Turkmenistan",
    A: "25",
    B: "12",
    C: "5",
    Total: "42",
    Award: "Official participation",
  },
  {
    Rank: "193",
    Name: "Esoev Anri",
    Country: "Tajikistan",
    A: "34.5",
    B: "6",
    C: "0",
    Total: "40.5",
    Award: "Official participation",
  },
  {
    Rank: "194",
    Name: "Navid Tawsif",
    Country: "Bangladesh",
    A: "25",
    B: "12",
    C: "0",
    Total: "37",
    Award: "Official participation",
  },
  {
    Rank: "194",
    Name: "Wali E Zaman",
    Country: "Bangladesh",
    A: "25",
    B: "12",
    C: "0",
    Total: "37",
    Award: "Official participation",
  },
  {
    Rank: "194",
    Name: "Si In Lei",
    Country: "Macau",
    A: "25",
    B: "12",
    C: "0",
    Total: "37",
    Award: "Official participation",
  },
  {
    Rank: "197",
    Name: "HRM Rafsan Amin",
    Country: "Bangladesh",
    A: "25",
    B: "6",
    C: "5",
    Total: "36",
    Award: "Official participation",
  },
  {
    Rank: "197",
    Name: "Sameer Mohammed Showkat",
    Country: "Bangladesh",
    A: "25",
    B: "6",
    C: "5",
    Total: "36",
    Award: "Official participation",
  },
  {
    Rank: "197",
    Name: "Deera Wijesundara",
    Country: "Sri Lanka",
    A: "25",
    B: "6",
    C: "5",
    Total: "36",
    Award: "Official participation",
  },
  {
    Rank: "197",
    Name: "Najmuddin Narkulyev",
    Country: "Turkmenistan",
    A: "8",
    B: "12",
    C: "16",
    Total: "36",
    Award: "Official participation",
  },
  {
    Rank: "197",
    Name: "Yhlas Amanmyradov",
    Country: "Turkmenistan",
    A: "8",
    B: "12",
    C: "16",
    Total: "36",
    Award: "Official participation",
  },
  {
    Rank: "202",
    Name: "Agageldi Gadamov",
    Country: "Turkmenistan",
    A: "25",
    B: "0",
    C: "5",
    Total: "30",
    Award: "Official participation",
  },
  {
    Rank: "202",
    Name: "Akmuhammet Shohratgeldiyev",
    Country: "Turkmenistan",
    A: "25",
    B: "0",
    C: "5",
    Total: "30",
    Award: "Official participation",
  },
  {
    Rank: "202",
    Name: "Kasym Kochekov",
    Country: "Turkmenistan",
    A: "25",
    B: "0",
    C: "5",
    Total: "30",
    Award: "Official participation",
  },
  {
    Rank: "205",
    Name: "Saidov Aminjon Shukhratovich",
    Country: "Tajikistan",
    A: "25",
    B: "0",
    C: "0",
    Total: "25",
    Award: "Official participation",
  },
  {
    Rank: "206",
    Name: "Xuan Li",
    Country: "New Zealand",
    A: "8",
    B: "6",
    C: "0",
    Total: "14",
    Award: "Official participation",
  },
  {
    Rank: "206",
    Name: "U A Sethmin Dinisuru",
    Country: "Sri Lanka",
    A: "8",
    B: "6",
    C: "0",
    Total: "14",
    Award: "Official participation",
  },
  {
    Rank: "208",
    Name: "Ganganath Kevin Ravindu Bandara Ranatunga",
    Country: "Sri Lanka",
    A: "8",
    B: "0",
    C: "5",
    Total: "13",
    Award: "Official participation",
  },
  {
    Rank: "209",
    Name: "Nicolas Martens",
    Country: "New Zealand",
    A: "0",
    B: "6",
    C: "5",
    Total: "11",
    Award: "Official participation",
  },
  {
    Rank: "210",
    Name: "E D S M Tharusha Senarathne",
    Country: "Sri Lanka",
    A: "8",
    B: "0",
    C: "0",
    Total: "8",
    Award: "Official participation",
  },
  {
    Rank: "210",
    Name: "Ali Omar Tahboub",
    Country: "Jordan",
    A: "8",
    B: "0",
    C: "0",
    Total: "8",
    Award: "Official participation",
  },
  {
    Rank: "210",
    Name: "Lisara Manumitha Jeewandara",
    Country: "Sri Lanka",
    A: "8",
    B: "0",
    C: "0",
    Total: "8",
    Award: "Official participation",
  },
  {
    Rank: "213",
    Name: "Lawrence Wen",
    Country: "New Zealand",
    A: "0",
    B: "0",
    C: "5",
    Total: "5",
    Award: "Official participation",
  },
  {
    Rank: "213",
    Name: "Vicky Zhao",
    Country: "New Zealand",
    A: "0",
    B: "0",
    C: "5",
    Total: "5",
    Award: "Official participation",
  },
  {
    Rank: "215",
    Name: "Mahmoud Amer Al-Haqash",
    Country: "Jordan",
    A: "0",
    B: "0",
    C: "0",
    Total: "0",
    Award: "Official participation",
  },
  {
    Rank: "215",
    Name: "Qais Mowaffaq Hanandeh",
    Country: "Jordan",
    A: "0",
    B: "0",
    C: "0",
    Total: "0",
    Award: "Official participation",
  },
];

const getAwardColor = (award: string) => {
  switch (award.toLowerCase()) {
    case "gold":
      return "bg-yellow-100 text-yellow-800";
    case "silver":
      return "bg-gray-100 text-gray-800";
    case "bronze":
      return "bg-orange-100 text-orange-800";
    default:
      return "bg-blue-100 text-blue-800";
  }
};
</script>

<template>
  <div class="min-h-screen bg-blue-50 py-12">
    <div class="container mx-auto px-4">
      <h1 class="mb-8 text-center text-4xl font-bold text-[#345CFE]">
        APIO 2025 Results
      </h1>

      <!-- Table Container with horizontal scroll -->
      <div
        class="relative w-full overflow-x-auto rounded-lg bg-white shadow-lg"
      >
        <div class="min-w-[800px]">
          <table class="w-full">
            <!-- Table Header -->
            <thead class="bg-gray-50">
              <tr>
                <th
                  class="sticky left-0 z-10 bg-gray-50 px-4 py-3 text-left text-sm font-semibold text-gray-600 sm:px-6"
                >
                  Rank
                </th>
                <th
                  class="sticky left-[60px] z-10 bg-gray-50 px-4 py-3 text-left text-sm font-semibold text-gray-600 sm:px-6"
                >
                  Name
                </th>
                <th
                  class="px-4 py-3 text-left text-sm font-semibold text-gray-600 sm:px-6"
                >
                  Country
                </th>
                <th
                  class="px-4 py-3 text-center text-sm font-semibold text-gray-600 sm:px-6"
                >
                  Problem A
                </th>
                <th
                  class="px-4 py-3 text-center text-sm font-semibold text-gray-600 sm:px-6"
                >
                  Problem B
                </th>
                <th
                  class="px-4 py-3 text-center text-sm font-semibold text-gray-600 sm:px-6"
                >
                  Problem C
                </th>
                <th
                  class="px-4 py-3 text-center text-sm font-semibold text-gray-600 sm:px-6"
                >
                  Total
                </th>
                <th
                  class="px-4 py-3 text-center text-sm font-semibold text-gray-600 sm:px-6"
                >
                  Award
                </th>
              </tr>
            </thead>

            <!-- Table Body -->
            <tbody class="divide-y divide-gray-200">
              <tr
                v-for="entry in rankingData"
                :key="entry.Rank"
                class="transition-colors duration-200 hover:bg-gray-50"
              >
                <td
                  class="sticky left-0 z-10 bg-white p-4 text-sm font-medium text-gray-900 sm:px-6"
                >
                  {{ entry.Rank }}
                </td>
                <td
                  class="sticky left-[60px] z-10 bg-white p-4 text-sm text-gray-900 sm:px-6"
                >
                  {{ entry.Name }}
                </td>
                <td class="whitespace-nowrap p-4 text-sm text-gray-900 sm:px-6">
                  {{ entry.Country }}
                </td>
                <td
                  class="whitespace-nowrap p-4 text-center text-sm text-gray-900 sm:px-6"
                >
                  {{ entry.A }}
                </td>
                <td
                  class="whitespace-nowrap p-4 text-center text-sm text-gray-900 sm:px-6"
                >
                  {{ entry.B }}
                </td>
                <td
                  class="whitespace-nowrap p-4 text-center text-sm text-gray-900 sm:px-6"
                >
                  {{ entry.C }}
                </td>
                <td
                  class="whitespace-nowrap p-4 text-center text-sm font-semibold text-gray-900 sm:px-6"
                >
                  {{ entry.Total }}
                </td>
                <td class="whitespace-nowrap p-4 text-center text-sm sm:px-6">
                  <span
                    :class="[
                      'inline-flex rounded-full px-2 py-1 text-xs font-semibold',
                      getAwardColor(entry.Award),
                    ]"
                  >
                    {{ entry.Award }}
                  </span>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
/* Add smooth transitions */
tr {
  transition: all 0.2s ease-in-out;
}

/* Custom scrollbar styles */
.overflow-x-auto {
  scrollbar-width: thin;
  scrollbar-color: #cbd5e0 #f7fafc;
}

.overflow-x-auto::-webkit-scrollbar {
  height: 8px;
}

.overflow-x-auto::-webkit-scrollbar-track {
  background: #f7fafc;
  border-radius: 4px;
}

.overflow-x-auto::-webkit-scrollbar-thumb {
  background-color: #cbd5e0;
  border-radius: 4px;
}

.overflow-x-auto::-webkit-scrollbar-thumb:hover {
  background-color: #a0aec0;
}

/* Ensure table is responsive */
@media (max-width: 640px) {
  .container {
    padding: 0 0.5rem;
  }

  h1 {
    font-size: 1.75rem;
    margin-bottom: 1rem;
  }
}
</style>
