// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/18/2025, 3:23:09 PM
const configMerger = require("/Users/sarvarkhursandov/Documents/gos/ioi.landing/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.ts")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/Users/sarvarkhursandov/Documents/gos/ioi.landing/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sarvarkhursandov/Documents/gos/ioi.landing/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sarvarkhursandov/Documents/gos/ioi.landing/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sarvarkhursandov/Documents/gos/ioi.landing/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sarvarkhursandov/Documents/gos/ioi.landing/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sarvarkhursandov/Documents/gos/ioi.landing/plugins/**/*.{js,ts,mjs}","/Users/sarvarkhursandov/Documents/gos/ioi.landing/composables/**/*.{js,ts,mjs}","/Users/sarvarkhursandov/Documents/gos/ioi.landing/utils/**/*.{js,ts,mjs}","/Users/sarvarkhursandov/Documents/gos/ioi.landing/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/sarvarkhursandov/Documents/gos/ioi.landing/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/sarvarkhursandov/Documents/gos/ioi.landing/app.config.{js,ts,mjs}"] } }));

module.exports = (() => {const cfg=config;cfg["content"]["files"]["19"] = "/Users/sarvarkhursandov/Documents/gos/ioi.landing/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";;return cfg;})()
