// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/17/2025, 12:43:00 PM
const configMerger = require("/Users/sarvarkhursandov/Documents/uzbekcoders/apio/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.ts")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/Users/sarvarkhursandov/Documents/uzbekcoders/apio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sarvarkhursandov/Documents/uzbekcoders/apio/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sarvarkhursandov/Documents/uzbekcoders/apio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sarvarkhursandov/Documents/uzbekcoders/apio/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sarvarkhursandov/Documents/uzbekcoders/apio/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sarvarkhursandov/Documents/uzbekcoders/apio/plugins/**/*.{js,ts,mjs}","/Users/sarvarkhursandov/Documents/uzbekcoders/apio/composables/**/*.{js,ts,mjs}","/Users/sarvarkhursandov/Documents/uzbekcoders/apio/utils/**/*.{js,ts,mjs}","/Users/sarvarkhursandov/Documents/uzbekcoders/apio/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/sarvarkhursandov/Documents/uzbekcoders/apio/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/sarvarkhursandov/Documents/uzbekcoders/apio/app.config.{js,ts,mjs}"] } }));

module.exports = (() => {const cfg=config;cfg["content"]["files"]["19"] = "/Users/sarvarkhursandov/Documents/uzbekcoders/apio/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";;return cfg;})()
